2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_setup.py:_flush():76] Configure stats pid to 12022
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_setup.py:_flush():76] Loading settings from /home/austi/.config/wandb/settings
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_setup.py:_flush():76] Loading settings from /home/austi/documents/OhioUniversity/gameAI/PA4/TensorRTS/enn/TensorRTS/wandb/settings
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'enn/TensorRTS/train.py', 'program': '/home/austi/documents/OhioUniversity/gameAI/PA4/TensorRTS/enn/TensorRTS/train.py'}
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_init.py:_log_setup():461] Logging user logs to /home/austi/documents/OhioUniversity/gameAI/PA4/TensorRTS/enn/TensorRTS/wandb/run-20240405_172159-zddvd6y1/logs/debug.log
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_init.py:_log_setup():462] Logging internal logs to /home/austi/documents/OhioUniversity/gameAI/PA4/TensorRTS/enn/TensorRTS/wandb/run-20240405_172159-zddvd6y1/logs/debug-internal.log
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_init.py:init():495] calling init triggers
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'env': {'kwargs': '{}', 'id': 'MoveToOrigin', 'validate': True}, 'net': {'embd_pdrop': 0.0, 'resid_pdrop': 0.0, 'attn_pdrop': 0.0, 'n_layer': 2, 'n_head': 2, 'd_model': 32, 'pooling': None, 'relpos_encoding': None, 'd_qk': 16, 'translation': None}, 'optim': {'lr': 0.005, 'lr_warmup_steps': None, 'bs': 512, 'weight_decay': 0.0, 'micro_bs': None, 'anneal_lr': True, 'update_epochs': 3, 'max_grad_norm': 2.0}, 'ppo': {'gae': True, 'gamma': 0.99, 'gae_lambda': 0.95, 'norm_adv': True, 'clip_coef': 0.2, 'clip_vloss': True, 'ent_coef': 0.1, 'vf_coef': 0.5, 'target_kl': None, 'anneal_entropy': True}, 'rollout': {'steps': 32, 'num_envs': 64, 'processes': 4}, 'eval': None, 'vf_net': None, 'name': 'config', 'seed': 1, 'total_timesteps': 50000, 'max_train_time': None, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'TensorRTS', 'wandb_entity': '', 'capture_samples': None, 'capture_logits': False, 'capture_samples_subsample': 1, 'trial': None, 'data_dir': '.', 'cuda_empty_cache': False}
2024-04-05 17:21:59,880 INFO    MainThread:12022 [wandb_init.py:init():548] starting backend
2024-04-05 17:21:59,880 INFO    MainThread:12022 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-05 17:21:59,882 INFO    MainThread:12022 [backend.py:ensure_launched():217] starting backend process...
2024-04-05 17:21:59,883 INFO    MainThread:12022 [backend.py:ensure_launched():222] started backend process with pid: 12155
2024-04-05 17:21:59,883 INFO    MainThread:12022 [wandb_init.py:init():558] backend started and connected
2024-04-05 17:21:59,885 INFO    MainThread:12022 [wandb_init.py:init():634] updated telemetry
2024-04-05 17:21:59,887 INFO    MainThread:12022 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2024-04-05 17:22:29,888 INFO    MainThread:12022 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2024-04-05 17:22:29,888 ERROR   MainThread:12022 [wandb_init.py:init():674] backend process timed out
2024-04-05 17:22:29,888 ERROR   MainThread:12022 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2024-04-05 17:22:29,893 ERROR   MainThread:12022 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    backend.cleanup()
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/austi/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
